export {AttendanceClientService} from './attendance-client.service'
export {CourseClientService} from './course-client.service'
export {CourseOfferingClientService} from './course-offering-client.service'
export {LocationClientService} from './location-client.service'
export {SessionClientService} from './session-client.service'
export {StudentClientService} from './student-client.service'
export {TimeSlotClientService} from './time-slot-client.service'
